name: SlimeNodes Auto Coin

on:
  workflow_dispatch:  # 仅手动触发，无自动定时

jobs:
  earn-coins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run auto coin
        env:
          SLIME_SESSION: ${{ secrets.SLIME_SESSION }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python slimenodes.py
